# -- Theme Parameters --

colorScheme = "fire"
defaultAppearance = "dark"
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]

[header]
  layout = "fixed-fill-blur"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"
  homepageImage = "img/cover.jpg"
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "posts"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showWordCount = false
  showZenMode = false

[list]
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  showSummary = true
  showCards = true
  cardView = true
  cardViewScreenWidth = false
  orderByWeight = true

[taxonomy]
  showTermCount = true
  showBreadcrumbs = true
  cardView = true

[term]
  showBreadcrumbs = true
  showTableOfContents = true
  groupByYear = false
  cardView = true
